/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AudioMessage: typeof import('./src/components/messages/AudioMessage.vue')['default']
    GetErrorSuccess: typeof import('./src/components/utils/GetErrorSuccess.vue')['default']
    ImageMessage: typeof import('./src/components/messages/ImageMessage.vue')['default']
    PageContainer: typeof import('./src/components/PageContainer.vue')['default']
    'PageContainer.bak': typeof import('./src/components/PageContainer.bak.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    WhoIs: typeof import('./src/components/WhoIs.vue')['default']
  }
}
